print("Hello")
print("I am luka")
print("I am 12 years old")
print("i love playing football")
print("and i love learnin codes")
print("Yeah")
print("I love GOA")
print("Its very interesting")
print("i have 2 hobbys")
print("And")
print("That is playing football")
print("And coding in GOA")
print("idk")
print("Goal oriented academy")
print("i dont knoww")
print("what to type")
print("i turn 13 in august")
print("1")
print("2")
print("3")
print("4")
print("5")
print("6")
print("i am 6")
print("nah im just kidding")
print("okay")
print("Thank you")
print("For reading this")
print("bye")
print(".")